# Sample .travis.yml for R projects from https://github.com/craigcitro/r-travis

language: r
warnings_are_errors: false
sudo: required

bioc_packages:
    - snpStats

notifications:
    email:
        on_success: change
        on_failure: change