expect_s4_class(enrichment(), "Enrichment")
expect_s4_class(enrichment(), "Enrichment")
expect_false(snpEnrichment:::is.enrichment(list()))
expect_false(snpEnrichment:::is.enrichment(1))
expect_true(snpEnrichment:::is.enrichment(enrichment()))
expect_true(all(snpEnrichment:::is.enrichment(c(enrichment(), enrichment()))))
expect_equivalent(snpEnrichment:::is.enrichment(list(enrichment(), b = "char")), c(TRUE, FALSE))
expect_equivalent(snpEnrichment:::is.enrichment(c(enrichment(), b = list(12, enrichment()))), c(TRUE, FALSE, TRUE))
expect_type(print(enrichment(), what = "All"), "list")
expect_output(show(enrichment()))
