# expect_s4_class(enrichment(), "Enrichment")
# expect_s4_class(enrichment(), "Enrichment")
# expect_false(is.enrichment(list()))
# expect_false(is.enrichment(1))
# expect_true(is.enrichment(enrichment()))
# expect_true(all(is.enrichment(c(enrichment(), enrichment()))))
# expect_equivalent(is.enrichment(list(enrichment(), b = "char")), c(TRUE, FALSE))
# expect_equivalent(is.enrichment(c(enrichment(), b = list(12, enrichment()))), c(TRUE, FALSE, TRUE))
# expect_s3_class(print(enrichment(), what = "All"), "data.frame")
# expect_output(show(enrichment()))
